services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: matee
      POSTGRES_PASSWORD: matee
      POSTGRES_DB: matee
    restart: always
    networks:
      - lesson
networks:
  lesson: